export const MOCK_ROWS = {
  INVENTORY: [
    ['ITEM_ID','ITEM_NAME','CATEGORY','DIMENSIONS','CURRENT_STOCK','UOM','MIN_ALERT_LEVEL','LOCATION_BIN'],
    ['SMC-0001','MS Sheet 2mm','Raw Material','2400x1200x2','50','Kg','10','Rack A1'],
    ['SMC-0002','MS Pipe 50mm','Raw Material','Ø50mm x 6m','30','Mtr','5','Yard B'],
    ['SMC-0003','Zinc Primer','Consumable','','20','Ltr','5','Store C'],
  ],
  ENQUIRY: [
    ['ENQUIRY_ID','TIMESTAMP','CLIENT_NAME','ITEM_DESC','QUANTITY','UNIT_COST','MARGIN_PCT','TOTAL_QUOTE','STATUS'],
    ['ENQ-202601-0001','2026-01-15','Acme Infrastructure','MS Security Gate','2','45000','15','103500','PO Received'],
    ['ENQ-202601-0002','2026-01-20','Bharat Constructions','Staircase Railing','1','28000','15','32200','Quoted'],
  ],
  PRODUCTION: [
    ['JOB_ID','CLIENT_NAME','STAGE','ASSIGNED_TO','STATUS','START_DATE','DUE_DATE','ESTIMATED_HOURS','ACTUAL_HOURS','WEIGHT_KG'],
    ['ENQ-202601-0001','Acme Infrastructure','Welding','raj@smc.in','In-Progress','2026-01-18','2026-02-05','40','22',''],
  ],
  PURCHASE: [['PURCHASE_ID','DATE','SUPPLIER','ITEM_ID','ITEM_DESC','QUANTITY','RATE','AMOUNT','GST_PCT','GST_AMOUNT','TOTAL','INVOICE_NO','INVOICE_DATE','PAYMENT_STATUS','PAID_AMOUNT','JOB_REF']],
  PAYMENT:  [['PAYMENT_ID','DATE','TYPE','ENQUIRY_REF','CLIENT_NAME','AMOUNT','MODE','REFERENCE','RECEIPT_NO','NOTES']],
  EXPENSE:  [['EXPENSE_ID','DATE','CATEGORY','DESCRIPTION','AMOUNT','GST_APPLICABLE','GST_AMOUNT','PAID_TO','JOB_REF','PAYMENT_MODE','APPROVED_BY']],
  DISPATCH: [['DISPATCH_ID','DATE','JOB_REF','CLIENT_NAME','DELIVERY_MODE','DELIVERY_ADDRESS','CHALLAN_NO','VEHICLE_NO','TRANSPORTER','FREIGHT_COST','WEIGHT_KG','NO_OF_PACKAGES','RECEIVED_BY','RECEIPT_DATE','POD_LINK','STATUS']],
  FOLLOWUP: [['FOLLOWUP_ID','ENQUIRY_REF','CLIENT_NAME','FOLLOWUP_DATE','METHOD','ASSIGNED_TO','NOTES','OUTCOME','NEXT_ACTION','NEXT_DATE','CREATED_AT']],
}
