export const SPREADSHEET_ID = import.meta.env.VITE_SPREADSHEET_ID as string;

export const SHEET_RANGES = {
  INVENTORY:  'Master_Inventory!A:H',
  PRICING:    'Price_Registry!A:E',
  ENQUIRY:    'Enquiry_Master!A:I',
  PRODUCTION: 'Production_Queue!A:J',
  PURCHASE:   'Purchase_Register!A:P',
  PAYMENT:    'Payment_Tracker!A:J',
  EXPENSE:    'Expense_Ledger!A:K',
  DISPATCH:   'Dispatch_Log!A:P',
  FOLLOWUP:   'Followup_Log!A:K',
} as const;

export type SheetKey = keyof typeof SHEET_RANGES;

// Column index maps — matches schema/*.json order
export const COL = {
  INVENTORY: {
    ITEM_ID: 0, ITEM_NAME: 1, CATEGORY: 2, DIMENSIONS: 3,
    CURRENT_STOCK: 4, UOM: 5, MIN_ALERT_LEVEL: 6, LOCATION_BIN: 7,
  },
  ENQUIRY: {
    ENQUIRY_ID: 0, TIMESTAMP: 1, CLIENT_NAME: 2, ITEM_DESC: 3,
    QUANTITY: 4, UNIT_COST: 5, MARGIN_PCT: 6, TOTAL_QUOTE: 7, STATUS: 8,
  },
  PRODUCTION: {
    JOB_ID: 0, CLIENT_NAME: 1, STAGE: 2, ASSIGNED_TO: 3,
    STATUS: 4, START_DATE: 5, DUE_DATE: 6, ESTIMATED_HOURS: 7,
    ACTUAL_HOURS: 8, WEIGHT_KG: 9,
  },
  PURCHASE: {
    PURCHASE_ID: 0, DATE: 1, SUPPLIER: 2, ITEM_ID: 3, ITEM_DESC: 4,
    QUANTITY: 5, RATE: 6, AMOUNT: 7, GST_PCT: 8, GST_AMOUNT: 9,
    TOTAL: 10, INVOICE_NO: 11, INVOICE_DATE: 12, PAYMENT_STATUS: 13,
    PAID_AMOUNT: 14, JOB_REF: 15,
  },
  PAYMENT: {
    PAYMENT_ID: 0, DATE: 1, TYPE: 2, ENQUIRY_REF: 3, CLIENT_NAME: 4,
    AMOUNT: 5, MODE: 6, REFERENCE: 7, RECEIPT_NO: 8, NOTES: 9,
  },
  EXPENSE: {
    EXPENSE_ID: 0, DATE: 1, CATEGORY: 2, DESCRIPTION: 3, AMOUNT: 4,
    GST_APPLICABLE: 5, GST_AMOUNT: 6, PAID_TO: 7, JOB_REF: 8,
    PAYMENT_MODE: 9, APPROVED_BY: 10,
  },
  DISPATCH: {
    DISPATCH_ID: 0, DATE: 1, JOB_REF: 2, CLIENT_NAME: 3, DELIVERY_MODE: 4,
    DELIVERY_ADDRESS: 5, CHALLAN_NO: 6, VEHICLE_NO: 7, TRANSPORTER: 8,
    FREIGHT_COST: 9, WEIGHT_KG: 10, NO_OF_PACKAGES: 11, RECEIVED_BY: 12,
    RECEIPT_DATE: 13, POD_LINK: 14, STATUS: 15,
  },
  FOLLOWUP: {
    FOLLOWUP_ID: 0, ENQUIRY_REF: 1, CLIENT_NAME: 2, FOLLOWUP_DATE: 3,
    METHOD: 4, ASSIGNED_TO: 5, NOTES: 6, OUTCOME: 7, NEXT_ACTION: 8,
    NEXT_DATE: 9, CREATED_AT: 10,
  },
} as const;
